version: "3.9"

services:
  client:
    build: ./todo-client
    ports:
      - "5173:5173"
    env_file:
      - ./todo-client/.env
    volumes:
      - ./todo-client:/app:cached
      - /app/node_modules
    depends_on:
      - server
    networks:
      - todo-network

  server:
    build: ./todo-server
    ports:
      - "8000:8000"
    env_file:
      - ./todo-server/.env
    volumes:
      - ./todo-server:/app:cached
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-network

volumes:
  mongo_data:

networks:
  todo-network:
    driver: bridge