# pull the latest image of node
FROM node:latest

# initialize a working directory
WORKDIR /app

# copy package.json files and install dependencies
COPY package*.json /app/

RUN npm install

# copy the rest of the app source code including .env
COPY . /app

# expose the app port (adjust to your app's port)
EXPOSE 8000

# command to run the app
CMD ["npm","run","dev"]